import { UssdCode } from "./types";

/**
 * Valeurs INITIALES uniquement (seed). Une fois importées en base via
 * /api/admin/seed, elles sont modifiables à volonté depuis le dashboard admin
 * (/admin/ussd-codes) sans toucher au code. Ce fichier ne sert qu'au premier
 * démarrage ou pour réinitialiser.
 */
export const DEFAULT_USSD_CODES: UssdCode[] = [
  // ---------- MTN ----------
  {
    id: "mtn_transfert",
    operateur: "mtn",
    categorie: "transfert",
    label: "Dépôt / Transfert vers client (MTN)",
    sequenceBrute: "*840#",
    etapes: [
      { input: "3", label: "Dépôt Mobile Money", waitMs: 4000 },
      { input: "1", label: "Abonné Mobile Money", waitMs: 4000 },
      { input: "{numero}", label: "Numéro abonné", waitMs: 4000 },
      { input: "{numero}", label: "Confirmer numéro", waitMs: 4000 },
      { input: "{montant}", label: "Montant", waitMs: 4000 },
      { input: "1", label: "Motif transaction", waitMs: 4000 },
      { input: "{code}", label: "Code secret marchand", waitMs: 6000 },
    ],
    actif: true,
  },
  {
    id: "mtn_credit_simple",
    operateur: "mtn",
    categorie: "credit_simple",
    label: "Vente crédit simple (MTN)",
    sequenceBrute: "*840*50*{numero}*{montant}#",
    actif: true,
  },
  {
    id: "mtn_retrait_abonne",
    operateur: "mtn",
    categorie: "retrait",
    label: "Retrait abonné (MTN)",
    sequenceBrute: "*840*54*{numero}*{montant}#",
    actif: true,
  },
  {
    id: "mtn_forfait_internet_jour",
    operateur: "mtn",
    categorie: "forfait_internet",
    label: "Forfait Internet Jour (MTN)",
    sequenceBrute: "*840*123*1*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_internet_semaine",
    operateur: "mtn",
    categorie: "forfait_internet",
    label: "Forfait Internet Semaine (MTN)",
    sequenceBrute: "*840*123*2*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_internet_mois",
    operateur: "mtn",
    categorie: "forfait_internet",
    label: "Forfait Internet Mois (MTN)",
    sequenceBrute: "*840*123*3*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_internet_illimite",
    operateur: "mtn",
    categorie: "forfait_internet",
    label: "Forfait Internet Illimité (MTN)",
    sequenceBrute: "*840*123*4*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_gopack_jour",
    operateur: "mtn",
    categorie: "forfait_gopack",
    label: "Forfait GoPack Jour (MTN)",
    sequenceBrute: "*840*172*1*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_gopack_semaine",
    operateur: "mtn",
    categorie: "forfait_gopack",
    label: "Forfait GoPack Semaine (MTN)",
    sequenceBrute: "*840*172*2*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_gopack_mois",
    operateur: "mtn",
    categorie: "forfait_gopack",
    label: "Forfait GoPack Mois (MTN)",
    sequenceBrute: "*840*172*3*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_maxi_jour",
    operateur: "mtn",
    categorie: "forfait_maxi",
    label: "Forfait Maxi Jour (MTN)",
    sequenceBrute: "*840*173*1*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_maxi_semaine",
    operateur: "mtn",
    categorie: "forfait_maxi",
    label: "Forfait Maxi Semaine (MTN)",
    sequenceBrute: "*840*173*2*{numero}#",
    actif: true,
  },
  {
    id: "mtn_forfait_maxi_mois",
    operateur: "mtn",
    categorie: "forfait_maxi",
    label: "Forfait Maxi Mois (MTN)",
    sequenceBrute: "*840*173*3*{numero}#",
    actif: true,
  },

  // ---------- MOOV ----------
  {
    id: "moov_transfert",
    operateur: "moov",
    categorie: "transfert",
    label: "Dépôt / Transfert vers client (Moov)",
    sequenceBrute: "*811*1*1*1*{numero}*{numero}*{montant}#",
    actif: true,
  },
  {
    id: "moov_retrait",
    operateur: "moov",
    categorie: "retrait",
    label: "Retrait d'argent (Moov)",
    sequenceBrute: "*811*2*2*{numero}*{numero}*{montant}#",
    actif: true,
  },
  {
    id: "moov_credit_simple",
    operateur: "moov",
    categorie: "credit_simple",
    label: "Vente crédit simple (Moov)",
    sequenceBrute: "*811*3*2*{numero}*{montant}*{code}#",
    actif: true,
  },
  {
    id: "moov_pass_bonus",
    operateur: "moov",
    categorie: "forfait_bonus",
    label: "Pass Bonus (Moov)",
    sequenceBrute: "*173*1*{montant}*{numero}*2*{code}#",
    actif: true,
  },
  {
    id: "moov_forfait_minute",
    operateur: "moov",
    categorie: "forfait_appel",
    label: "Forfait Minute (Moov)",
    sequenceBrute: "*173*{montant}*{numero}*2*{code}#",
    actif: true,
  },
  {
    id: "moov_forfait_internet",
    operateur: "moov",
    categorie: "forfait_internet",
    label: "Forfait Internet (Moov)",
    sequenceBrute: "*123*8*{numero}*{montant}*{code}#",
    actif: true,
  },

  // ---------- CELTIIS ----------
  {
    id: "celtiis_transfert",
    operateur: "celtiis",
    categorie: "transfert",
    label: "Dépôt / Transfert vers client (Celtiis)",
    sequenceBrute: "*889*3*1*{numero}*{montant}#",
    actif: true,
  },
  {
    id: "celtiis_retrait",
    operateur: "celtiis",
    categorie: "retrait",
    label: "Retrait (Celtiis)",
    sequenceBrute: "*889*40*{numero}*{montant}#",
    actif: true,
  },
  {
    id: "celtiis_credit_simple",
    operateur: "celtiis",
    categorie: "credit_simple",
    label: "Vente crédit simple (Celtiis)",
    sequenceBrute: "*889*50*{numero}*{numero}*{montant}#",
    actif: true,
  },
  {
    id: "celtiis_forfait_appel_jour",
    operateur: "celtiis",
    categorie: "forfait_appel",
    label: "Forfait Appel Jour (Celtiis)",
    sequenceBrute: "*889*173*{numero}*1#",
    actif: true,
  },
  {
    id: "celtiis_forfait_appel_semaine",
    operateur: "celtiis",
    categorie: "forfait_appel",
    label: "Forfait Appel Semaine (Celtiis)",
    sequenceBrute: "*889*173*{numero}*2#",
    actif: true,
  },
  {
    id: "celtiis_forfait_appel_mois",
    operateur: "celtiis",
    categorie: "forfait_appel",
    label: "Forfait Appel Mois (Celtiis)",
    sequenceBrute: "*889*173*{numero}*3#",
    actif: true,
  },
  {
    id: "celtiis_forfait_interne_jour",
    operateur: "celtiis",
    categorie: "forfait_internet",
    label: "Forfait Interne Jour (Celtiis)",
    sequenceBrute: "*889*123*{numero}*1#",
    actif: true,
  },
  {
    id: "celtiis_forfait_interne_semaine",
    operateur: "celtiis",
    categorie: "forfait_internet",
    label: "Forfait Interne Semaine (Celtiis)",
    sequenceBrute: "*889*123*{numero}*2#",
    actif: true,
  },
  {
    id: "celtiis_forfait_interne_mois",
    operateur: "celtiis",
    categorie: "forfait_internet",
    label: "Forfait Interne Mois (Celtiis)",
    sequenceBrute: "*889*123*{numero}*3#",
    actif: true,
  },
  {
    id: "celtiis_forfait_mymix_jour",
    operateur: "celtiis",
    categorie: "forfait_mymix",
    label: "Forfait My Mix Jour (Celtiis)",
    sequenceBrute: "*889*172*{numero}*1#",
    actif: true,
  },
  {
    id: "celtiis_forfait_mymix_semaine",
    operateur: "celtiis",
    categorie: "forfait_mymix",
    label: "Forfait My Mix Semaine (Celtiis)",
    sequenceBrute: "*889*172*{numero}*2#",
    actif: true,
  },
  {
    id: "celtiis_forfait_mymix_mois",
    operateur: "celtiis",
    categorie: "forfait_mymix",
    label: "Forfait My Mix Mois (Celtiis)",
    sequenceBrute: "*889*172*{numero}*3#",
    actif: true,
  },
  {
    id: "celtiis_forfait_illimite_semaine",
    operateur: "celtiis",
    categorie: "forfait_illimite",
    label: "Forfait Illimité Semaine (Celtiis) — à confirmer",
    sequenceBrute: "*889*123*4*{numero}*2#",
    actif: false,
  },
  {
    id: "celtiis_forfait_illimite_mois",
    operateur: "celtiis",
    categorie: "forfait_illimite",
    label: "Forfait Illimité Mois (Celtiis) — à confirmer",
    sequenceBrute: "*889*123*4*{numero}*3#",
    actif: false,
  },
];
